### ISSUE TITLE
razercfg qrazercfg error

### ISSUE THREAD

**Issue by cr1ogen** [mbuesch/razer#30] opened 2014-11-03 19:41 UTC
when i try change profile give me this error

Traceback (most recent call last):
  File "/usr/local/bin/qrazercfg", line 333, in activeChanged
    razer.setActiveProfile(self.mouseWidget.mouse, self.profileId)
  File "/usr/local/lib/python3.4/dist-packages/pyrazer/main.py", line 580, in setActiveProfile
    return self.__recvU32()
  File "/usr/local/lib/python3.4/dist-packages/pyrazer/main.py", line 381, in __recvU32
    return self.__receiveExpectedMessage(self.sock, self.REPLY_ID_U32)
  File "/usr/local/lib/python3.4/dist-packages/pyrazer/main.py", line 372, in __receiveExpectedMessage
    id, payload = self.__receive(sock)
  File "/usr/local/lib/python3.4/dist-packages/pyrazer/main.py", line 334, in __receive
    id = hdr[0]
IndexError: index out of range
Traceback (most recent call last):
  File "/usr/local/bin/qrazercfg", line 640, in pollNotifications
    n = razer.pollNotifications()
  File "/usr/local/lib/python3.4/dist-packages/pyrazer/main.py", line 402, in pollNotifications
    pack = self.__receive(self.sock)
  File "/usr/local/lib/python3.4/dist-packages/pyrazer/main.py", line 334, in __receive
    id = hdr[0]
IndexError: index out of range
Traceback (most recent call last):
  File "/usr/local/bin/qrazercfg", line 485, in freqChanged
    razer.setFrequency(self.mouseWidget.mouse, self.profileId, freq)
  File "/usr/local/lib/python3.4/dist-packages/pyrazer/main.py", line 317, in __sendCommand
    self.__send(cmd)
  File "/usr/local/lib/python3.4/dist-packages/pyrazer/main.py", line 299, in __send
    self.sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/local/bin/qrazercfg", line 658, in reconfig
    razer.rescanDevices()
  File "/usr/local/lib/python3.4/dist-packages/pyrazer/main.py", line 414, in rescanDevices
    self.rescanMice()
  File "/usr/local/lib/python3.4/dist-packages/pyrazer/main.py", line 410, in rescanMice
    self.__sendCommand(self.COMMAND_ID_RESCANMICE)
  File "/usr/local/lib/python3.4/dist-packages/pyrazer/main.py", line 317, in __sendCommand
    self.__send(cmd)
  File "/usr/local/lib/python3.4/dist-packages/pyrazer/main.py", line 299, in __send
    self.sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe

Debian GNU/Linux kernel 3.18.0-rc3 x86_64 GNU/Linux

Mouse Razer Deathadder 3500dpi Left-Handed Edition

**Comment by mbuesch** [comment] 2015-03-11 18:25
I'm not sure what is happening there.
Do you have a clean install without old library or server components from previous versions?
Try to uninstall everything (with uninstall.sh) and re-install, please.

**Comment by mbuesch** [comment] 2015-04-01 15:35
I'm closing this, because I cannot reproduce it with current versions.
If this still happens for you, please re-open the bug.

Thanks for your bug report.

**Comment by cr1ogen** [comment] 2016-08-25 19:44
Use the last version, i have a clean install 
Now when i try change profile give me this error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyrazer/ui.py", line 661, in pollNotifications
    n = razer.pollNotifications()
  File "/usr/local/lib/python3.5/dist-packages/pyrazer/main.py", line 445, in pollNotifications
    pack = self.__receive(self.sock)
  File "/usr/local/lib/python3.5/dist-packages/pyrazer/main.py", line 377, in __receive
    id = hdr[0]
IndexError: index out of range
When i close qrazercfg and i want running again give this
Failed to connect to razerd socket: [Errno 111] Connection refused
I have to restart systemctl razerd and again have the error above
Debian GNU/Linux kernel 4.6 x86_64

**Comment by mbuesch** [comment] 2016-08-25 19:53
Please start razerd with full debugging output `razerd -l3` and try to reproduce the problem.
Then paste the output here.

**Comment by mbuesch** [comment] 2016-10-16 17:36
Could you please try to reproduce this with debugging enabled?
I cannot reproduce this and I don't get reports from other people about this.

**Comment by mbuesch** [comment] 2017-01-01 12:03
@cr1ogen 
Could you please try to reproduce with debugging enabled?
I still can't reproduce this and I don't get reports from other people having this issue. So this might be a bug that only occurs on your system.
So I need your help to track this down. Otherwise I will have to close this issue again and leave it unresolved.
Thanks for your support.

**Comment by mbuesch** [comment] 2017-01-21 10:55
Closing this issue as "can't reproduce".
Please re-open the issue, if the problem persists and information on how to reproduce is available.
Thanks for your support.

**Closed by mbuesch** 2017-01-21 10:55 UTC
Labels: bug, can't reproduce
