### ISSUE TITLE
DA Chroma logo LED color changing isn't working

### ISSUE THREAD

**Issue by medicalwei** [mbuesch/razer#67] opened 2016-03-14 03:09 UTC
Hi,

I try to fiddle with the LEDs of the mouse. While the scroll wheel LED does change, the LED on the logo doesn't, along with an error message only when I try to set the color:
```
➜  razer git:(master) ✗ razercfg -c GlowingLogo:666666
Failed to set LED color (Errorcode 6: Failure)
```

What diagnose steps do I need to take? I can try to use another computer with Windows/Mac though.

**Comment by z3ntu** [comment] 2016-03-14 07:53
I actually have the Deathadder Chroma and it worked for me some time ago...

**Comment by mbuesch** [comment] 2016-03-14 16:22
I'm not aware of any issues here.

@medicalwei  and @z3ntu What firmware versions do you have?

**Comment by z3ntu** [comment] 2016-03-14 18:24
Just tested it with `qrazercfg` and everything works as expected. I have the Deathadder Chroma `model no. RZ01-0121`.
Also using `razercfg -c GlowingLogo:666666` in the terminal works.

**Comment by medicalwei** [comment] 2016-03-15 03:27
Same model no. (RZ01-0121) and firmware version (3.01) here.

**Comment by medicalwei** [comment] 2016-03-15 03:31
Sorry but I am considering this problem of my mouse now. The error message does not come out, but the glowing logo does not glow. Trying on the Mac driver.

**Comment by medicalwei** [comment] 2016-03-15 03:39
Seems that I turned the LED off using the official driver, and I cannot turn it on using razercfg.
LED color changing works after turning the LED back on using synapse.

**Comment by mbuesch** [comment] 2016-03-15 16:16
Ok, the only way to debug this is to look at the USB traffic and see what we are doing differently from the original driver. Wireshark can be used for this.
I don't have the hardware, so I can't do that myself.

**Comment by medicalwei** [comment] 2016-03-21 05:53
Sorry for the late update. The captured traffics of the original driver is uploaded below:
[DAChroma-USBPcaps.zip](https://github.com/mbuesch/razer/files/181721/DAChroma-USBPcaps.zip)

Please don't hesitate if you have further need of testing/capturing/etc.

**Comment by medicalwei** [comment] 2016-03-21 06:20
And here's the USB traffic capture from razercfg. 
[razercfg-dachroma.zip](https://github.com/mbuesch/razer/files/181730/razercfg-dachroma.zip)

**Comment by kzemek** [comment] 2016-03-22 12:21
A bit of insight: when I wrote the Chroma driver, Synapse LED toggle (or indeed any other setting if I remember correctly) had no permanent effect on the mouse. It may be a capability added in a later firmware upgrade, with old opcodes preserved for compatibility but the permanent "off" state taking precedence over temporary states that razercfg sets.

**Comment by john-2000** [comment] 2016-04-25 20:06
Hi
I have a DeathAdder Chroma USB 
lsusb: _ID 1532:0043 Razer USA, Ltd_ 
Firmware version 5.02 
and I am experiencing the same thing -- ie I can set LED from the qrazercfg tool but not from CLI razercfg.
Is there anything I can do to help to get this fixed?

**Comment by kzemek** [comment] 2016-04-25 20:09
@john-2000 This seems like a different issue, unless @medicalwei can change the LED color from qrazercfg?

**Comment by john-2000** [comment] 2016-04-25 20:38
Ok, this is odd it now works from the command line - I added a razer.conf file by hand and now:
`razercfg -c GlowingLogo:ffff77
razercfg -m ScrollWheel:spectrum
razercfg -c ScrollWheel:ff0000` 

all work just fine -- thanks for the great tool !! (and thanks for the fast response)

**Comment by mbuesch** [comment] 2016-07-09 07:50
I'm closing this, because there doesn't seem to be a way to find the cause of the original issue.
If the problem re-appears, please re-open this issue.
Thanks!

**Closed by mbuesch** 2016-07-09 07:50 UTC
Labels: bug, need more information
