### ISSUE TITLE
/etc/razer.conf apparently not loaded / applied to DA:Chroma

### ISSUE THREAD

**Issue by john-2000** [mbuesch/razer#76] opened 2016-05-17 18:06 UTC
@mbuesch hi thanks for answering my other post about this - here as a new issue

Sorry but I am probably a bit slow her, I have been trying to get my deathadder chroma to change settings to move from spectrum to fixed colours (and if possible the DPI - I am little unsure about the comments following #49 (comment) )

I have re-downloaded the razer-master.zip and run the install with

> cmake .
> make
> sudo make install

installation looked sucessful but my /etc/razer.conf does not seem affect the mouse settings - ideally I would like static light in faint yellow (bbbb00) on both scrollwheel and body and a 2 resolution setting of 1500 dpi applied.

my /etc/razer.conf looks like this:

>     [Mouse:DeathAdder Chroma::]
>     # Config section disabled?
>     disabled=false
>     # Configure first profile
>     # Resolution: 800, 1500, 2200, 5600, 10000
>     res=1:1500
>     # Frequency: 125, 500, 1000
>     freq=1:500
>     # Initial profile selection
>     profile=1
>     # Configure LEDs
>     led=1:GlowingLogo:on
>     mode=1:GlowingLogo:static
>     color=1:GlowingLogo:bbbb00
>     led=1:Scrollwheel:on
>     mode=1:Scrollwheel:static
>     color=1:Scrollwheel:bbbb00

could you help me get this right? I seem to need to run qrazercfg to adjust the DPI and run razercfg -m Scrollwheel:static -m GlowingLogo:static -c GlowingLogo:bbbb00 -c ScrollWheel:bbbb00 to adjust the colours

all help is appreciated, thanks

**Comment by mbuesch** [comment] 2016-06-01 16:04
It's a bit hard for me to find out what's going on here.
Does the config work in general for you? Are other settings like DPI or led on/off applied correctly?

**Comment by jediafr** [comment] 2016-06-03 13:12
Hi,
i have a DA:Chroma on my Arch linux rig.

I'm experiencing the same issue described above : 
the /etc/razor.conf file i copied is ignored by razord.
The settings work throught the QT client though (DPI, Leds and colors).

**Comment by mbuesch** [comment] 2016-06-03 15:33
@jediafr 
> /etc/razor.conf 

A file named like this certainly needs a good shave and it's 100% correct that razerd ignores bearded files.

**Comment by jediafr** [comment] 2016-06-03 16:18
Ahah I quote your readme file : 
The user may create a razerd configuration file in /etc/razer.conf which can be used to specify various razerd options

**Comment by haoanw** [comment] 2016-06-30 00:15
@mbuesch @john-2000 for me, every setting from qrazercfg is working, but the file /etc/razer.conf is ignored. how exactly should i change it here? my file looks like this:

`...........
# Razer DeathAdder Chroma mouse
[Mouse:DeathAdder Chroma:USB-003:1532-0043-SI1608121710420]
	# Config section disabled?
	disabled=false

	# Configure first profile
	# Resolution: 800, 1800, 3500, 5600, 10000
	res=1:1000
	# Frequency: 125, 500, 1000
	freq=1:1000

	# Initial profile selection
	profile=1

	# Configure LEDs
	led=1:GlowingLogo:on
	mode=1:GlowingLogo:static
	color=1:GlowingLogo:bbbb00
	led=1:Scrollwheel:on
	mode=1:Scrollwheel:static
	color=1:Scrollwheel:0000FF

# Razer DeathAdder mouse
...........`

**Comment by mbuesch** [comment] 2016-06-30 05:29
```
 [Mouse:DeathAdder Chroma:USB-003:1532-0043-SI1608121710420]
```

Most likely the identification is wrong.
It doesn't really make sense to hard code the USB number here, because that changes all the time.
Please use globs (see the other examples).

**Comment by jediafr** [comment] 2016-06-30 07:23
Here's my section (of razer.conf) and the conf file isnt loaded....sadly
[Mouse:DeathAdder Chroma:*:*]
        # Config section disabled?
        disabled=false

        # Configure first profile
        # Resolution: 800, 1800, 3500, 5600, 10000
        res=1:1000
        # Frequency: 125, 500, 1000
        freq=1:500

        # Initial profile selection
        profile=1

        # Configure LEDs
        led=1:GlowingLogo:off
        led=1:Scrollwheel:off
        mode=1:Scrollwheel:static
        color=1:Scrollwheel:0000FF

**Comment by haoanw** [comment] 2016-06-30 10:28
now i change the device ID to `[Mouse:DeathAdder Chroma:*:*]` , it won't be loaded;
then i change the device ID to `[Mouse:DeathAdder Chroma::]`, it also won't get loaded.
but qrazercfg works fine, anyone know what is going on here?

**Comment by jediafr** [comment] 2016-06-30 12:01
no one knows,  mbuesch there is an issue there, i can get you more info if only you give me the instructions.

**Comment by mbuesch** [comment] 2016-06-30 15:46
Well, I don't have that device.

Could you please run razerd with full debugging?
```
$ sudo systemctl stop razerd
$ sudo ./razerd/razerd -l3
```

Please post the output.

**Comment by jediafr** [comment] 2016-06-30 16:06
Here you go :

sudo razerd -l3
Razer device service daemon
[razerd debug]: librazer: profile emulation: Committed active profile
[razerd debug]: librazer: Mouse profile emulation initialized for
Mouse:DeathAdder Chroma:USB-006:1532-0043-PM1501121713168
[razerd debug]: librazer: Applying config section "Mouse:DeathAdder
Chroma:*:*" to "Mouse:DeathAdder
Chroma:USB-006:1532-0043-PM1501121713168"
librazer: Config section "Mouse:DeathAdder Chroma:*:*" item "res" invalid.
librazer: Failed to apply initial config to "Mouse:DeathAdder
Chroma:USB-006:1532-0043-PM1501121713168"
[razerd debug]: librazer: Allocated and initialized new mouse
"Mouse:DeathAdder Chroma:USB-006:1532-0043-PM1501121713168"
[razerd debug]: Broadcasting mouse-add event


2016-06-30 17:46 UTC+02:00, Michael Büsch <notifications@github.com>:
> Well, I don't have that device.
>
> Could you please run razerd with full debugging?
> ```
> $ sudo systemctl stop razerd
> $ sudo ./razerd/razerd -l3
> ```
>
> Please post the output.
>
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/mbuesch/razer/issues/76#issuecomment-229700579


-- 
Kinds regards,

Jean-denis.

**Comment by haoanw** [comment] 2016-06-30 16:14
Hi, here is mine:
`viki@barney:/usr/local/bin$ sudo ./razerd -l3
Razer device service daemon
[razerd debug]: librazer: profile emulation: Committed active profile
[razerd debug]: librazer: Mouse profile emulation initialized for Mouse:DeathAdder Chroma:USB-003:1532-0043-SI1608121710420
[razerd debug]: librazer: Applying config section "Mouse:DeathAdder Chroma:*:*" to "Mouse:DeathAdder Chroma:USB-003:1532-0043-SI1608121710420"
librazer: Config section "Mouse:DeathAdder Chroma:*:*" item "res" invalid.
librazer: Failed to apply initial config to "Mouse:DeathAdder Chroma:USB-003:1532-0043-SI1608121710420"
[razerd debug]: librazer: Allocated and initialized new mouse "Mouse:DeathAdder Chroma:USB-003:1532-0043-SI1608121710420"
`

**Comment by mbuesch** [comment] 2016-06-30 16:23
```
librazer: Config section "Mouse:DeathAdder Chroma::" item "res" invalid.
```

This is not a bug, but a known missing feature.
See https://github.com/mbuesch/razer/issues/73 and https://github.com/mbuesch/razer/issues/49#issuecomment-139571978

Please continue the discussion in https://github.com/mbuesch/razer/issues/73, if you want to implement this feature.
So I'm going to close this issue, because we already have (at least) one issue for this topic.

**Closed by mbuesch** 2016-06-30 16:23 UTC
Labels: duplicate

**Comment by jediafr** [comment] 2016-06-30 16:24
Thanks Michael, so what is the remedy ? 
comment off the res ?

**Comment by haoanw** [comment] 2016-06-30 16:28
thanks for your reply, i set res to 800 and it worked, still don't understand it fully:(

**Comment by mbuesch** [comment] 2016-06-30 16:28
>comment off the res ?

Either that, or specify a res that already has an existing mapping. You can change the mappings to your desire in qrazercfg and load one of these existing mappings via razer.conf or razercfg.

**Comment by mbuesch** [comment] 2016-06-30 16:31
>still don't understand it fully:(

DPI dual thingie on some Razer mice.
There always is a table of DPI values to select from. But for some mice (like the DA Chroma) there's also the possibility to modify the table entries. So you can basically create a table that you can later select from. That currently is only supported by qrazercfg.
If the res you specified is not in that table already, razer.conf and razercfg will fail.

**Comment by haoanw** [comment] 2016-07-01 10:52
> DPI is a dual thingie on some Razer mice.
There always is a table of DPI values to select from. But for some mice (like the DA Chroma) there's also the possibility to modify the table entries. So you can basically create a table that you can later select from. 
thanks for your reply, now i seem understand better. it seems that there is already a table of DPI mapping in razerd (5 already exist value [800] [1800] ...etc), could you please tell me where the table is stored and then i could try to modified the value inside :)

**Comment by mbuesch** [comment] 2016-07-01 15:56
>could you please tell me where the table is stored and then i could try to modified the value inside :)

The table is what you can see in the lower half of qrazercfg, below the profiles tabs and above the LEDs.

**Comment by jediafr** [comment] 2016-07-02 11:08
Thanks again for helping us...
those "possible scan resolutions" is the table.

I have to set those manually in qrazercfg each time i reboot the computer.


2016-07-01 17:56 UTC+02:00, Michael Büsch <notifications@github.com>:
>>could you please tell me where the table is stored and then i could try to
>> modified the value inside :)
>
> The table is what you can see in the lower half of qrazercfg, below the
> profiles tabs and above the LEDs.
>
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/mbuesch/razer/issues/76#issuecomment-229983155


-- 
Kinds regards,

Jean-denis.
