### ISSUE TITLE
Setting Environment for OS with systemd

### ISSUE THREAD

**Issue by deekej** [mbuesch/razer#68] opened 2016-03-16 12:02 UTC
After installation, trying to enable the razerd (via 'systemctl start razerd') will fail on Fedora, because the service can't find the librazer.so.1.

The easiest way to fix it is to change the _razer.service.template_ - here's the diff:
[diff.txt](https://github.com/mbuesch/razer/files/175896/diff.txt)

Alternatively, you can mention this in the README.md file - if this happen to any user, he should add the line below into the razer.service.template (in [Service] section) and run the make again:

_Environment=LD_LIBRARY_PATH=/usr/local/lib_

**Comment by z3ntu** [comment] 2016-03-16 16:00
The problem is that `librazer.so.1` is not guaranteed to be in `/usr/local/lib`

**Comment by mbuesch** [comment] 2016-03-16 16:05
>Environment=LD_LIBRARY_PATH=/usr/local/lib

No. This is not a correct fix.
If you install razercfg to /usr/local it is your responsibility to make sure the installed libraries can be found.

```make install``` will already run ldconfig. If you installed it somewhere, where ldconfig cannot find it, it's a configuration error of your operating system or you installed it to the wrong place.
If your operating system ships an /etc/ld.so.conf*, which includes /usr/local/lib, everything is fine. It your operating system doesn't ship that and you don't want to add that to ld.co.conf, simply don't install razercfg to that location.

So I don't see this as an issue of razercfg.

**Comment by z3ntu** [comment] 2016-03-16 16:06
@mbuesch Maybe it would be good to add this as a note to the readme (as it gets installed to `/usr/local` without further configuration)

**Comment by mbuesch** [comment] 2016-03-16 16:12
@z3ntu I think a sane operating system should already have /usr/local/lib in its ld.so.conf.
But you are right. We could add a small note to the readme. Perhaps:
```
Be aware that make install installs the shared library librazer.so to ${install_prefix}/lib.
You you have to make sure that it can be found there by the dynamic linker ld.so.
This can be done via /etc/ld.so.conf or /etc/ld.so.conf.d/.
See your operating system manual for further information.
```

**Comment by z3ntu** [comment] 2016-03-16 16:14
Maybe also that it is installed to `/usr/local/` by default, and maybe that you can change the prefix with `-DCMAKE_INSTALL_PREFIX='<somewhere>'`.

**Comment by mbuesch** [comment] 2016-03-16 16:23
@z3ntu OK. Feel free do do a pull request.

**Comment by z3ntu** [comment] 2016-03-16 16:47
I actually have no idea how to phrase that :D

**Comment by mbuesch** [comment] 2016-03-16 18:01
```
Be aware that make install installs the shared library librazer.so to $PREFIX/lib.
The default $PREFIX is /usr/local/, but the install prefix can also be changed via -DCMAKE_INSTALL_PREFIX='<somewhere>'
You you have to make sure that librazer.so in $PREFIX/lib/ can be found by the dynamic linker ld.so.
Your operating system most likely already has support for libraries in /usr/local/lib. So on most systems you don't have to do anything.
If this is not the case, or you installed razercfg somewhere else, a new library search path can be added via /etc/ld.so.conf or /etc/ld.so.conf.d/.
See your operating system manual for further information.
```

?

**Comment by mbuesch** [comment] 2016-03-16 19:24
Closing this issue, because we added a note to the README.

If you still think this is a problem and should be fixed in another way, re-open please.
Thanks a lot for your report.

**Closed by mbuesch** 2016-03-16 19:24 UTC
Labels: invalid

**Comment by deekej** [comment] 2016-03-19 20:02
No, I think this is a good solution. :) Thank you very much!
